### ISSUE TITLE
Creating the appsync backend

### ISSUE THREAD

**Issue by d0ruk** [aws-samples/aws-mobile-appsync-chat-starter-angular#1]
This is more of a question rather than an issue.

It looks like the appsync features are set-up by .sh scripts.

I noticed that the Awsmobile CLI is about to roll out an appsync feature. Is that going to be a js implementation of the steps carried out in the .sh files?

If so, assuming all backend init/teardown will be taken care of by awsmobile-cli, what dependencies of this project would be discarded if upgraded?

**Comment by onlybakam** [comment]
hey @d0ruk 
the helper scripts are simply to help with the process of creating your resources. We may change these later on if/when we get other forms of support for creating AppSync API resources. This wont change the main project however.
