### ISSUE TITLE
error TS2688: Cannot find type definition file for 'paho-mqtt'.

### ISSUE THREAD

**Issue by CBedzz** [aws-samples/aws-mobile-appsync-chat-starter-angular#10]
when building project with awsmobile run, I get the following error:

```"ERROR in node_modules/aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.d.ts(1,23): error TS2688: Cannot find type definition file for 'paho-mqtt'.```

From the amplify repo, found the following fix:

You need to install these for type definitions
```npm i –save-dev @types/zen-observable```
```npm i –save-dev @types/paho-mqtt```

**Comment by onlybakam** [comment]
you may have been testing with a new version of Amplify.
I specifically tested with 0.2.9 release and it does not contain the PubSub folder under lib.

where you able to get things working?

**Comment by CBedzz** [comment]
Yes, it worked fine after installing the two @types modules noted above.

**Comment by onlybakam** [comment]
awesome!
