### ISSUE TITLE
Message Table Partition and Sort Key

### ISSUE THREAD

**Issue by bssawais** [aws-samples/aws-mobile-appsync-chat-starter-angular#15]
Hey, with reference to below execution
--attribute-definitions AttributeName=conversationId,AttributeType=S AttributeName=createdAt,AttributeType=S 
--key-schema AttributeName=conversationId,KeyType=HASH AttributeName=createdAt,KeyType=RANGE

Means that Table 
Primary partition key | conversationId (String)
Primary sort key | createdAt (String)

Question is what will happen when both users sent a message at same timeStamp (createdAt) for the same conversation?

Thanks

**Comment by onlybakam** [comment]
thanks for pointing this out. actually there is a way to handle this:

```typescript
    const date = Date.now();
    const mID = uuid();
    const message: Message = {
      conversationId: this.conversation.id,
      content: this.message,
      createdAt: `${date}`,
      sender: this.senderId,
      isSent: false,
      id : `${date}-${mID}`
    };
```

`createdAt` should be the same as `id`. the added uuid adds the necessary uniqueness. we'll get that fixed and pushed out.

**Comment by onlybakam** [comment]
changes pushed to master branch
