### ISSUE TITLE
--api-id is undefined if deployment region does not support appsync

### ISSUE THREAD

**Issue by d0ruk** [aws-samples/aws-mobile-appsync-chat-starter-angular#2]
Hello,

The ```--api-id``` variable in ```setup.sh``` is (naturally) undefined if the region ```awsmobile push``` was to a region that doesn't have the service endpoint.

Adding a note to Step 3 in the README might prevent future questions.

Here it is for your copy/pasta convenience;

Copy the file ./backend/mobile-hub-project.yml to ./awsmobilejs/backend/ and push the configuration change to AWS Mobile Hub. Note that, the region you deploy your backend resources to, must have [AWS Appsync support](https://aws.amazon.com/blogs/mobile/aws-appsync-region-expansion-and-new-features-for-api-keys/). To check the awsmobile-cli region: ```awsmobile configure```.

**Comment by onlybakam** [comment]
Added this clarification in prerequisites:

* [AWS Mobile CLI](https://github.com/aws/awsmobile-cli) (configured for a region where [AWS AppSync is available](https://docs.aws.amazon.com/general/latest/gr/rande.html#appsync_region))
