### ISSUE TITLE
Checking NodeJS?

### ISSUE THREAD

**Issue by Wieljer** [aws-samples/aws-mobile-appsync-chat-starter-angular#27]
Question - Hi just saw your project from the amazon blog. I'm interested in trying it out today. Curious though what is NodeJS used for since AppSync should be handling messages? Sorry I haven't dug in, i'm just looking at the serverless portion of this project.

**Comment by Wieljer** [comment]
Okay I got the project up and running. I see now, it looks like you still need to host this on a server / EC2 instance so that you can launch nodejs for web client. I thinking it would run from an S3 bucket or something and not need runtime.

**Comment by awsed** [comment]
You can run `ng build` and copy the contents of the `dist` folder to your web server of choice. The command `awsmobile publish` does that automatically, including uploading the build to S3
