### ISSUE TITLE
Cannot find module '../../AppSync.js'

### ISSUE THREAD

**Issue by d0ruk** [aws-samples/aws-mobile-appsync-chat-starter-angular#3]
Hello,

The default file name used by the AWS console is ```AppSync.json```.

*In addition to* changing line 3 of ```appsync.service.ts``` to

```import appSyncConfig from '../../AppSync.json';```

One needs to declare *.json modules in ```typings.d.ts```

```
declare module "*.json" {
  const content: any;
  export default content;
}
```

**Comment by onlybakam** [comment]
make sure you select the **Web** tab to download the `AppSync.js` file

**Comment by d0ruk** [comment]
You're right. My bad.

**Comment by mrowles** [comment]
Does *Web* not exist anymore? Looks like it's just iOS, Android and JavaScript.
