### ISSUE TITLE
AppSync.js no longer available

### ISSUE THREAD

**Issue by ijin** [aws-samples/aws-mobile-appsync-chat-starter-angular#31]
The `AppSync.js` is no longer available. Only `was-exports.js` for JavaScript apps.

**Comment by Kasmilos** [comment]
It looks like the Web integration has been removed in favor of generic Javascript. The aws-export.js seems to contain the information needed, but not in the format previously expected.
I have not been able to get it to work.

**Comment by seiichi1101** [comment]
me neither!
fix please

**Comment by seiichi1101** [comment]
I resolved by creating AppSync.js and replacing like below

```
export default {
  "graphqlEndpoint": <your_endpoint>,
  "region": <your_region>,
  "authenticationType": <your_setting>,
  "apiKey": <your_apikey>
}
```

**Comment by awsed** [comment]
Our apologies, it seems there were some changes in the console. 

You should be able to download the aws-exports.js file, import it to:

https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular/blob/master/src/app/chat-app/appsync.service.ts

Then use both "aws_appsync_graphqlEndpoint" and "aws_appsync_region" from aws-exports.js under the client object.

We'll update the documentation and the code to reflect this. Thank you.

**Comment by Kasmilos** [comment]
Just one more thing to change in the new AppSync.js file:

`const appSyncConfig =  {`

**Comment by awsed** [comment]
Amplify CLI implementation is now merged, you shouldn't have this issue anymore
