### ISSUE TITLE
readme.md to describe setup process using aws-amplify instead of awsmobile which is obsolete

### ISSUE THREAD

**Issue by deepkamal** [aws-samples/aws-mobile-appsync-chat-starter-angular#33]
awsmobile is obsolete and process should describe installation/setup using aws-amplify

**Comment by awsed** [comment]
It does use AWS Amplify, just not the AWS Amplify CLI. When this was created the AWS Amplify CLI didn't exist and the AWS Mobile CLI was the tool of choice.

Eventually we'll work on porting it to the AWS Amplify CLI, when time allows, in the mean time pull requests are always very welcome.

**Comment by awsed** [comment]
Move to Amplify was just merged. You can use the new CLI from now on
