### ISSUE TITLE
AWS Appsync Chat - Clarifications

### ISSUE THREAD

**Issue by Pugalit** [aws-samples/aws-mobile-appsync-chat-starter-angular#39]
Hi All,

Can anyone please clarify my below doubts: 

1. How to enable the Group Chats in this code
2. How to enable the Notification for Online and Offline users  in this code

**Comment by awsed** [comment]
Group chats should be actually easy to implement. You just need to expose an existing conversation to other users and add the client logic to enable users to add themselves to the conversation. The backend should work fine out of the box without modifications.

By default when you click on a user it'll create a conversation automatically. You could potentially add the logic to allow selection of multiple users before creating the conversation then create a convo with multiple users.

With regards to online/offline. One option would be to add a boolean called "status" or "online" property to the User type in the GraphQL schema then update the field from the client when the user connects or open the app.
