### ISSUE TITLE
master angular

### ISSUE THREAD

**Issue by DevAxi** [aws-samples/aws-mobile-appsync-chat-starter-angular#40]
Hi

I seem to be struggling to get the master version to work.
(The new master version change from yesterday gets past ng serve step for me now)

I'm still having this issue though:
I did the production (https) publish version and it gives me a 404 error when trying to load the web app as can be seen below:

**This XML file does not appear to have any style information associated with it. The document tree is shown below.**
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>************</RequestId>
<HostId>
  *********************
</HostId>
</Error>
```
Just wondering if I am the only one that can't get this to work. Been at it for last 4 days and it's supposed to be a 15-30 min process... so clearly i'm doing something simple incorrectly.

**Comment by awsed** [comment]
Do you manage to get it running locally on http://localhost:4200 ? The error above looks like something related to S3 or CloudFront caching 4xx errors.

You can try to run:

```
amplify publish --invalidate-cache
```

Then wait about 10min for the invalidation to reach all global points of presence

**Comment by DevAxi** [comment]
Dear Ed

Thank you for the response.
It did load on the local machine. Didn't run through it by adding a user
etc.
On the published side it doesn't load through the browser.

I will try your suggestion and get back to you with whether it worked.

Appreciate the response.

Kind regards
Charl Bruwer

**Comment by DevAxi** [comment]
Ed,

Tested running it locally and it works fine, can add users successfully.
Opening 2 separate browsers with 2 different users allows for functionality to work perfectly.
Perhaps the only thing that might be off is, once I click more than once to add a conversation with a user it adds multiple conversations with a user. 

That being said, I waited for 20min after doing your publish --invalidate-cache command and no luck to get the Https hosting to work.
I will give it a few more hours and see if it corrects.

*********(I will edit this out if it happens to come right)**********************

If I do look at that error as mentioned in the first post of this thread it states: 
<error> 
<code>AccessDenied<code>    
Does that not mean that the s3 bucket has been setup incorrectly with regards to permissions or something?

You will have to forgive me but I am an absolute noob when it comes to anything AWS related, this is my first time using AWS.

**Comment by awsed** [comment]
Thank you for the info, it looks like the app itself is working fine. The problem looks to be related to publishing the site via Amplify CLI. I created an issue in the Amplify CLI repo: 

https://github.com/aws-amplify/amplify-cli/issues/611

You can follow the progress there. 

In the mean time it should be fixed if you go to the CloudFront console and manually change the S3 origin in Distribution Settings to use `<bucket name>.s3-<region>.amazonaws.com` (for example `chatql-hosting-bucket-s3-ap-southeast-2.amazonaws.com`.
