### ISSUE TITLE
User conversations are duplicated

### ISSUE THREAD

**Issue by kylekirkby** [aws-samples/aws-mobile-appsync-chat-starter-angular#41]
Hi @awsed,

Thanks for the awesome starter project. Should user conversations be duplicated if both users initiate a conversation with each other? 

This is probably more of a feature request but didn't know whether I'd configured it wrong some how. 

Many thanks,

Kyle

**Comment by kpjofficial** [comment]
I am seeing the duplicate conversations as well. 
For me, conversation with another user, is shown up 3 or more times but I can only one of the conversations is actually displaying the messages, rest are all empty.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/5809146/51663018-90412c80-1fdb-11e9-9339-db1a7172e9c1.png">

**Comment by awsed** [comment]
Closing for lack of response
