### ISSUE TITLE
NodeJS 6.10 No longer suppported

### ISSUE THREAD

**Issue by justinlevi** [aws-samples/aws-mobile-appsync-chat-starter-angular#46]
Seeing this error when going through the basic setup
```
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. 
```

Changing the `amplify/backend/analytics/awsmobileappsyncchat/pinpoint-cloudformation-template.json` to : 

"Runtime": "nodejs8.10",

Seems to get past the error.

**Comment by awsed** [comment]
This was an issue with amplify generated resources and it was fixed by the amplify team. It'll now generate a Lambda custom resource with a newer version.
