### ISSUE TITLE
Dealing with missed messages whilst offline + connection issue

### ISSUE THREAD

**Issue by patricknazar** [aws-samples/aws-mobile-appsync-chat-starter-angular#48]
When I have a chat going on two computers, A and B, and I disconnect B from the network entirely, it cannot receive messages from A, obviously. Then I send some messages from A. When I reconnect B, there are two problems:

1 - B misses the messages that it was supposed to get from A whilst B was offline
2 - It no longer receives messages from A, but can continue to send back to A.

If I refresh B, the whole conversation shows up and all returns to normal.

What I want: Once B gets back online, to receive the delta of messages that it missed.

This problem is a deal-breaker for me to use AppSync. What can I do here?

**Comment by awsed** [comment]
@patricknazar maybe this is what you're looking for: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html

Delta Sync is not implemented in this application. This is a sample app that doesn't have all AppSync features and doesn't reflect everything that can be done with the service. You can find more tutorials and sample apps in the community repository: https://github.com/aws/aws-appsync-community
