### ISSUE TITLE
Property 'subscribeToNewMessage' does not exist on type 'getConversationMessagesQuery'

### ISSUE THREAD

**Issue by liqsteffen** [aws-samples/aws-mobile-appsync-chat-starter-angular#49]
Im trying to get this running in **angular 8.0.0** which works local just fine. 
If i try to deploy it to a bucket with `ng build --prod` i get the following error:

`ERROR in xxx/chat-app/chat-message-view/chat-message-view.component.ts(108,71): error TS2339: Property 'subscribeToNewMessage' does not exist on type 'getConversationMessagesQuery'.`

The error is at this part from chat-message-view.component.ts:
`const observable: ObservableQuery<MessagesQuery> = client.watchQuery(options);`

If I change it to following it works:
`const observable: any = client.watchQuery(options);`

But without the `ObservableQuery<MessagesQuery>` type the query will not subscribe to the graphql API. Are you guys planning to do a Angular 8 version or you might be able to help on this one?

**Comment by dexster** [comment]
You're using a newer version of apollo-client in your project which is causing this. I'm still trying to see if I can get this statically typed in my project but for now you could just do this:

`const observable: ObservableQuery<any> = client.watchQuery(options);`
