### ISSUE TITLE
Can't find field conversations({"first":10}) on object --> Upgrade to Anuglar 8

### ISSUE THREAD

**Issue by liqsteffen** [aws-samples/aws-mobile-appsync-chat-starter-angular#51]
Im still on the path to upgrade this project to Angular 8.
At the moment i get the following error:
```
ERROR Error: Uncaught (in promise): Error: Can't find field conversations({"after":null,"first":10}) on object {
  "__typename": "User",
  "cognitoId": "76d3034f-f213-4d17-85da-564b0e1219ec",
  "username": "76d3034f-f213-4d17-85da-564b0e1219ec",
  "registered": true,
  "id": "76d3034f-f213-4d17-85da-564b0e1219ec"
}
```

Which is caused by

```
this.appsync.hc().then(client => {
  const options = {
    query: getUserConversationsConnection,
    variables: { first: constants.conversationFirst}
};
const userConvos = client.readQuery(options); 
```

I suppose the catch which im trying to read is empty. But I dont understand how it works on the acutal project?

Am i missing something?

**Comment by awsed** [comment]
Unfortunately Angular upgrades are painful in my experience. This app was first developed with Angular 5, then we managed to upgrade to Angular 6 and finally Angular 7. All upgrades caused breaking changes that were not trivial to fix. For now we're not supporting Angular 8 but you're very welcome to create a PR if you get it fixed.

This is working on Angular 7 and at this stage we're not working on an upgrade to Angular 8 to be able to troubleshoot this. it's not clear if something else in the upgrade process is breaking the call.

**Comment by lyvyu** [comment]
Hello @liqsteffen,
I got into this error as well, by any chance did you manage to solve the issue ?! 

**EDIT**
When reading query with `client.readQuery({...})` the exact same arguments should be passed for the query function.

Let's say first time you have these options:
```
  const options = {
    query: getUserConversationsConnection,
    variables: { first: constants.conversationFirst}
};
```
...the exact same options should be sent for the `readQuery` to work, otherwise, it throws this error.

Hope you managed to find the solution.
