### ISSUE TITLE
Integrating AWS-Amplify, AppSync with Ionic-4 application

### ISSUE THREAD

**Issue by pragatikP** [aws-samples/aws-mobile-appsync-chat-starter-angular#52]
Hi,
I've followed all the steps present in the documentation and pulled the project form https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular  when I completed all the configuration and tried $amplify serve it gives below error. Not sure what's going on here. Any guidance to fix this issue would be much appreciated. Thanks. I can provide any further information needed with respect to this issue.

> Project 'app' could not be found in workspace.
> [ng] Error: Project 'app' could not be found in workspace.

**Comment by awsed** [comment]
Please provide steps to replicate, I don't get this error
