### ISSUE TITLE
Are the request/response resolvers defined locally synced with `amplify push`?

### ISSUE THREAD

**Issue by andrew-aernos** [aws-samples/aws-mobile-appsync-chat-starter-angular#53]
I've been defining graphql resolvers using the AppSync console and manually attaching to each type online, this is not an ideal situation because 
- code changes are not tracked VCS, just whatever the latest snapshot is.
- VTL are not checked at all, at least syntax should be checked.

To my delight, I see in the the resolvers (.request / .response) are defined locally ./backend/resolvers. 

My question is will they be synced to the AWS when we call `amplify push`?

**Comment by awsed** [comment]
This sample doesn't use this functionality however it's possible to define resolvers and update them with `amplify push` using custom resolvers:

https://aws-amplify.github.io/docs/cli-toolchain/graphql#custom-resolvers

With this sample you have to use CloudFormation instead.
