### ISSUE TITLE
how to identify number of active subscribers by subscription in AppSync

### ISSUE THREAD

**Issue by kushptlapigarage** [aws-samples/aws-mobile-appsync-chat-starter-angular#56]
Need to keep count of how many subscribers are connected with each subscription.

For UserA, UserB are connected with SubscriptionA : then 2 is the total subscribers
For UserA are connected with SubscriptionB : then 1 is the total subscribers

Can i know when UserA unsubscribes , subscribes, disconnects, reconnects from AppSync ?

**Comment by awsed** [comment]
It's not included in the sample, you'd have to implement the logic for presence detection. It's not supported out of the box by AppSync.
