### ISSUE TITLE
nodejs8.10 is no longer supported error when doing amplify push

### ISSUE THREAD

**Issue by FrancisTse8** [aws-samples/aws-mobile-appsync-chat-starter-angular#57]
I cloned the code and did all the steps up to "amplify push". When I did that, I got the error
`CREATE_FAILED UserPoolClientLambda                                                                    AWS::Lambda::Function      Wed Jan 08 2020 12:46:25 GMT-0500 (Eastern Standard Time) The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. ... `
I saw a closed issue#46 with similar result where nodejs6.0 no longer supported. Author seemed to have changed the nodejs version and made things work. I saw a line of code `"Runtime": "nodejs8.10"` in the file nested-cloudformation-stack.yml in the amplify/backend/awscloudformation folder and changed it to "nodejs10.16.3". However, when I ran the "amplify push" again, my edited test was change back to "nodejs8.10" and still had the error.
Perhaps this is not the file to change?
The following are my running environment:
- nodejs is v10.16.3
- amplify is 3.15.0
- aws --version showed the following
aws-cli/1.16.290 Python/2.7.16 Darwin/18.7.0 botocore/1.13.26
- using VSC and it's terminal to execute the CLIs

Don't know if there are any other info I should provide. Hope this is enough. Any pointer as to what else to try is much appreciated!

**Comment by fbelhaouas** [comment]
Hi, I had the same issue, but after to update amplify to the latest version 4.13.1, the push is successful

**Comment by FrancisTse8** [comment]
I upgraded and push was successful also. Wish the error message provided better hint. Thanks for your reply!
