### ISSUE TITLE
Token not refreshing

### ISSUE THREAD

**Issue by NewToStuff** [aws-samples/aws-mobile-appsync-chat-starter-angular#8]
I think the token is expiring after about an hour an not refreshing. An uncaught error (401) then occurs.
I am not sure as to the best way to approach refreshing the token when required.

**Comment by awsed** [comment]
The token will expire after 1h. Automatically refreshing the token is not implemented in our code.

You'd need to implement some additional logic to use a Refresh Token provided by Cognito and request new ID/Access Tokens, more info on: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by NewToStuff** [comment]
Hi,

Thanks for your reply. Given this is an example to get people started with AppSync and given that token refresh is so fundamental and a bit difficult it would be really useful if one of the Angular examples covered it.  I appreciate that might not happen but it would be so helpful.

Thanks

**Comment by awsed** [comment]
Thank you for the suggestion/feature request. As a starter application, ChatQL presents initial the building blocks to build a serverless chat system with 1h tokens to secure/authN/Z access from users. 

We can work on adding the functionality or alternatively feel free to create a pull request with the logic to renew the tokens, whatever comes first.

**Comment by NewToStuff** [comment]
Hi,

Thanks for your response. I am trying to figure this out but read that https://github.com/aws/aws-amplify/issues/446. This seems to be indicating that the Amplify library should be automatically refreshing the token behind the scenes. If that is the case then is this actually a "bug"?

_

> _retwedt commented 2 days ago
> It would be nice to get some guidance on how to do this with the Amplify lib. It appears to me that the session is automatically refreshed if expired, but there is no way to refresh the token early. Is that the case?
> 
> @mlabieniec
> Collaborator
> mlabieniec commented 2 days ago
> @retwedt that's correct, **the session is automatically refreshed,** you could technically refresh the token yourself however by doing this same approach since the amplify lib uses the cognito lib under the covers. We are working on giving more flexibility / simplifying this as well (in our backlog) to both refresh and also disable automatic refresh._

_

https://github.com/aws/aws-amplify/issues/446

**Comment by awsed** [comment]
In that case it's best to bee tracked at the Amplify repo, not a bug in our app
