### ISSUE TITLE
Refresh token so no longer expires after 1 hour

### ISSUE THREAD

**Issue by NewToStuff** [aws-samples/aws-mobile-appsync-chat-starter-angular#9]
Would like to request an enhancement so that the JWT token is automatically refreshed. This would be particularly useful as token refreshing will be required for most SIngle Page Applications and the documentation on doing this is not clear - In particular there is very little for Angular use cases. 

This is a response to the feedback received on issue #8

**Comment by awsed** [comment]
Thank you for the suggestion/feature request. As a starter application, ChatQL presents initial the building blocks to build a serverless chat system with 1h tokens to secure/authN/Z access from users.

We can work on adding the functionality or alternatively feel free to create a pull request with the logic to renew the tokens, whatever comes first.
